name: moira
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flame: ^1.13.1
  flame_oxygen: ^0.1.9+6
  flame_audio: ^2.1.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  google_fonts: any
  flame_tiled: ^1.18.2
  async: any
  jenny: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  assets:
    - assets/images/
    - assets/images/class_sprites/
    - assets/tiles/
    - assets/audio/
    - assets/yarn/
    - assets/data/units.json
    - assets/data/items.json
    - assets/data/weapons.json
    - assets/data/attacks.json
    - assets/data/skills.json
    - assets/data/classes.json
    - assets/data/stages.json
  uses-material-design: true

