name: moira
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flame: any
  flame_oxygen: any
  flame_audio: any
  flutter:
    sdk: flutter
  flutter_animate: any
  google_fonts: any
  flame_tiled: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
    - assets/data/units.json
    - assets/data/items.json
    - assets/data/weapons.json
    - assets/data/attacks.json
    - assets/data/skills.json
    - assets/data/classes.json
    - assets/data/stages.json
  uses-material-design: true

